
name: Build and Push Docker Images

on:
  push:
    branches:
      - backend # backend 브랜치에 푸시될 때 실행

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v3

      # 3. MySQL Docker 이미지 빌드 및 푸시
      - name: Build MySQL Docker image
        working-directory: db # docker_test_db 폴더로 이동
        run: | #쉘 명령어(스크립트)를 실행
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dockerdb .

      - name: Push MySQL Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockerdb

      # 4. Backend Docker 이미지 빌드 및 푸시
      - name: Build Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dockerbackend .
      - name: Push Backend Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dockerbackend
  

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull and run
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.LIVE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |  #uses 키워드를 사용하여 액션을 호출할 때 입력 값(input) 으로 사용됨
            if [ "$(sudo docker ps -a -q -f name=dockerdb)" ]; then
              sudo docker rm -f dockerdb
            fi
            if [ "$(sudo docker ps -a -q -f name=dockerbackend)" ]; then
              sudo docker rm -f dockerbackend
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/dockerdb)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/dockerdb
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/dockerbackend)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/dockerbackend
            fi
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dockerdb
            sudo docker run -d -p 3308:3306 --name dockerdb -v dockerdb_volume:/var/lib/mysql ${{ secrets.DOCKERHUB_USERNAME }}/dockerdb
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dockerbackend
            sudo docker run -d -p 8080:8080 --name dockerbackend \
            -e  GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}} \
            -e GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}} \
            -e NAVER_CLIENT_ID=${{secrets.NAVER_CLIENT_ID}} \
            -e NAVER_CLIENT_SECRET=${{secrets.NAVER_CLIENT_SECRET}} \
            -e KAKAO_CLIENT_ID=${{secrets.KAKAO_CLIENT_ID}} \
            -e KAKAO_CLIENT_SECRET=${{secrets.KAKAO_CLIENT_SECRET}} ${{ secrets.DOCKERHUB_USERNAME }}/dockerbackend        
            




